//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ukrashenie
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    

    public partial class Timerzyanov_UkrashenieEntities : DbContext
    {

        private static Timerzyanov_UkrashenieEntities _context;

        public static Timerzyanov_UkrashenieEntities GetContext()
        {
            if (_context == null)
                _context = new Timerzyanov_UkrashenieEntities();
            return _context;
        }
        public Timerzyanov_UkrashenieEntities()
            : base("name=Timerzyanov_UkrashenieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderProduct> OrderProduct { get; set; }
        public virtual DbSet<PickUpPoint> PickUpPoint { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
